Django/prac/first_pjt/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('index/', views.index),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
]

Django/prac/first_pjt/first_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

Django/prac/first_pjt/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    
    def __str__(self):
        return f'{self.title}'

Django/prac/first_pjt/articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'articles/index.html')

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    print(request.GET.get('nickname'))
    return render(request, 'articles/catch.html')

Django/prac/first_pjt/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
<h1>여기는 catch 입니다</h1>
<a href="{% url 'articles:throw' %}">fadsfsda</a>
{% endblock content %}

Django/prac/first_pjt/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>여기는 인덱스 입니다</h1>
{% endblock content %}

Django/prac/first_pjt/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
<h1>여기는 throw 입니다</h1>

<form action="{% url 'articles:catch' %}">
  <label for="nickname">닉네임</label>
  <input type="text" name='nickname' id='nickname'>
  <input type="submit">
</form>
{% endblock content %}

Django/prac/first_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>